name: build

on:
  schedule:
    # 1:30am UTC is 7am IST depending on daylight savings.
    - cron: '30 13 * * *'

  # Allow manually triggering of the workflow.
  workflow_dispatch: {}
  
jobs:
  build_daily:
    runs-on: ubuntu-latest
    name: Build
    
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: esp-idf build
      uses: espressif/esp-idf-ci-action@v1
      with:
        esp_idf_version: v4.4
        target: esp32s2
        path: 'IIoT-Projeto-Manutencao-Preditiva-Maquinas-Girantes/src/IIoT-Projeto'
